### ISSUE TITLE
non-object errors in add_flagging_link_comment method

### ISSUE THREAD

**Issue by Vernal** [postmatic/crowd#23]
When posting a new comment, several errors are thrown in the Crowd_Control->add_flagging_link_comment() method.

They seem related to the comment object not being given to this filter from check_comment method in wp-includes/comment.php => $comment = apply_filters( 'comment_text', $comment );

$comment is just the comment text, but the comment object is missing.

Via:
https://wordpress.org/support/topic/non-object-errors-in-add_flagging_link_comment-method

**Comment by rlaan** [comment]
Hi Jason and Ronald

Thanks for taking the time to look into this.
I did do some further investigation to see why this doesn't work for us on WP 4.4.1.
The call in wp-includes/comment.php comes from check_comment(),
which is called by wp_allow_comment(), which is called from wp_new_comment().

I checked this part of the comment.php file for alterations coming from version 4.4 or even 4.3, but haven't found anything related. 

I do see the errors when making a new comment, so that coincides with the wp_new_comment method path.

Well I hope you can at least verify my results. 

Thanks!
Ruud

ps: because we are using several comments related hooks, I did switch over to a default theme (twentyfifteen) and got the same results:

0.0002  247056  {main}( )   .../wp-comments-post.php:0
2   0.4649  20716488    wp_handle_comment_submission( ) .../wp-comments-post.php:20
3   0.4663  20728616    wp_new_comment( )   .../comment.php:2793
4   0.4676  20739344    wp_allow_comment( ) .../comment.php:1713
5   0.4698  20741008    check_comment( )    .../comment.php:661
6   0.4699  20741088    apply_filters( )    .../comment.php:47
7   0.4709  20753760    call_user_func_array:{/var/www/wp/project.local/htdocs/wp-includes/plugin.php:235} ( )  .../plugin.php:235
8   0.4709  20753928    Crowd_Control->add_flagging_link_comment( ) .../plugin.php:235

**Comment by ronalfy** [comment]
I did an object test and if is not an object, returns the text.

https://github.com/postmatic/crowd/commit/c004c07618e26465a02ffa601041af9a7fa010a4
